### ISSUE TITLE
font-not-found

### ISSUE THREAD

**Issue by relleums** [fact-project/iact_coordinate_transformations#2]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "Libertinus Serif" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................

**Comment by maxnoe** [comment]
Libertinus Serif comes with a current TeX Live or can be downloaded here https://github.com/khaledhosny/libertinus
